"""Evaluate license-plate detection and character segmentation predictions.

The ground-truth CSV is generated by `convert_labelme_to_csv.py`. Prediction CSV
rows must contain at least:

- image_name
- method
- plate_bbox_pred: JSON [x, y, w, h]
- char_bboxes_pred: JSON [[x, y, w, h], ...]

All boxes use image coordinates, not ROI-local coordinates.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import pandas as pd


EXPECTED_CHAR_COUNT = 7
END_TO_END_CHAR_IOU_THRESHOLD = 0.45
REQUIRED_GT_COLUMNS = {
    "image_name",
    "split",
    "plate_x",
    "plate_y",
    "plate_w",
    "plate_h",
    "char_count_gt",
    "char_bboxes_gt",
}
REQUIRED_PRED_COLUMNS = {
    "image_name",
    "method",
    "plate_bbox_pred",
    "char_bboxes_pred",
}
OPTIONAL_PRED_COLUMNS = {
    "params": "",
    "runtime_ms": math.nan,
    "status": "",
    "failure_reason": "",
    "vis_path": "",
}


def is_empty_value(value: Any) -> bool:
    if value is None:
        return True
    if isinstance(value, float) and math.isnan(value):
        return True
    if isinstance(value, str) and value.strip().lower() in {"", "nan", "none", "null"}:
        return True
    return False


def normalize_bbox(box: Any) -> list[float] | None:
    if box is None:
        return None
    if not isinstance(box, (list, tuple)) or len(box) != 4:
        raise ValueError(f"bbox must be a 4-number list, got {box!r}")
    values = [float(item) for item in box]
    if any(math.isnan(item) or math.isinf(item) for item in values):
        raise ValueError(f"bbox contains non-finite values: {box!r}")
    if values[2] <= 0 or values[3] <= 0:
        return None
    return values


def parse_json_value(value: Any, field_name: str) -> Any:
    if is_empty_value(value):
        return None
    if isinstance(value, (list, tuple)):
        return value
    if not isinstance(value, str):
        raise ValueError(f"{field_name} must be JSON text, got {type(value).__name__}")
    text = value.strip()
    if text in {"[]", "null"}:
        return None
    return json.loads(text)


def parse_plate_bbox(value: Any) -> tuple[list[float] | None, str | None]:
    try:
        parsed = parse_json_value(value, "plate_bbox_pred")
        return normalize_bbox(parsed), None
    except Exception as exc:  # noqa: BLE001 - preserve row-level evaluation.
        return None, str(exc)


def parse_char_bboxes(value: Any) -> tuple[list[list[float]], str | None]:
    try:
        parsed = parse_json_value(value, "char_bboxes_pred")
        if parsed is None:
            return [], None
        if not isinstance(parsed, (list, tuple)):
            raise ValueError(f"char_bboxes_pred must be a list, got {parsed!r}")
        boxes: list[list[float]] = []
        for box in parsed:
            normalized = normalize_bbox(box)
            if normalized is not None:
                boxes.append(normalized)
        boxes.sort(key=lambda item: item[0])
        return boxes, None
    except Exception as exc:  # noqa: BLE001 - preserve row-level evaluation.
        return [], str(exc)


def bbox_iou(box_a: list[float] | None, box_b: list[float] | None) -> float:
    if box_a is None or box_b is None:
        return 0.0
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b
    ax2, ay2 = ax + aw, ay + ah
    bx2, by2 = bx + bw, by + bh
    inter_w = max(0.0, min(ax2, bx2) - max(ax, bx))
    inter_h = max(0.0, min(ay2, by2) - max(ay, by))
    inter_area = inter_w * inter_h
    union_area = aw * ah + bw * bh - inter_area
    if union_area <= 0:
        return 0.0
    return inter_area / union_area


def center_error(box_a: list[float] | None, box_b: list[float] | None) -> float:
    if box_a is None or box_b is None:
        return math.nan
    ax, ay, aw, ah = box_a
    bx, by, bw, bh = box_b
    acx, acy = ax + aw / 2.0, ay + ah / 2.0
    bcx, bcy = bx + bw / 2.0, by + bh / 2.0
    return math.hypot(acx - bcx, acy - bcy)


def boundary_error(pred_boxes: list[list[float]], gt_boxes: list[list[float]]) -> float:
    if len(pred_boxes) != len(gt_boxes) or not gt_boxes:
        return math.nan
    errors = []
    for pred, gt in zip(pred_boxes, gt_boxes):
        pred_left, pred_right = pred[0], pred[0] + pred[2]
        gt_left, gt_right = gt[0], gt[0] + gt[2]
        errors.append(abs(pred_left - gt_left) + abs(pred_right - gt_right))
    return float(sum(errors) / len(errors))


def mean_char_iou(pred_boxes: list[list[float]], gt_boxes: list[list[float]]) -> float:
    if len(pred_boxes) != len(gt_boxes) or not gt_boxes:
        return math.nan
    return float(sum(bbox_iou(pred, gt) for pred, gt in zip(pred_boxes, gt_boxes)) / len(gt_boxes))


def load_ground_truth(path: Path) -> pd.DataFrame:
    gt = pd.read_csv(path, encoding="utf-8-sig")
    missing = REQUIRED_GT_COLUMNS - set(gt.columns)
    if missing:
        raise SystemExit(f"Ground-truth CSV is missing columns: {sorted(missing)}")
    if len(gt) != 30:
        raise SystemExit(f"Ground-truth CSV should contain 30 rows, got {len(gt)}")
    if gt["image_name"].duplicated().any():
        duplicated = gt.loc[gt["image_name"].duplicated(), "image_name"].tolist()
        raise SystemExit(f"Ground-truth image_name duplicates: {duplicated}")
    if not (gt["char_count_gt"].astype(int) == EXPECTED_CHAR_COUNT).all():
        raise SystemExit("Ground-truth char_count_gt must be 7 for every row")
    return gt


def load_predictions(path: Path) -> pd.DataFrame:
    pred = pd.read_csv(path, encoding="utf-8-sig")
    missing = REQUIRED_PRED_COLUMNS - set(pred.columns)
    if missing:
        raise SystemExit(f"Prediction CSV is missing columns: {sorted(missing)}")
    for column, default in OPTIONAL_PRED_COLUMNS.items():
        if column not in pred.columns:
            pred[column] = default
    if pred[["image_name", "method"]].duplicated().any():
        duplicated = pred.loc[pred[["image_name", "method"]].duplicated(), ["image_name", "method"]]
        raise SystemExit(f"Prediction CSV has duplicate image_name + method rows:\n{duplicated}")
    return pred


def gt_plate_bbox(row: pd.Series) -> list[float]:
    return [
        float(row["plate_x"]),
        float(row["plate_y"]),
        float(row["plate_w"]),
        float(row["plate_h"]),
    ]


def gt_char_bboxes(row: pd.Series) -> list[list[float]]:
    parsed = json.loads(row["char_bboxes_gt"])
    boxes = [normalize_bbox(box) for box in parsed]
    if any(box is None for box in boxes) or len(boxes) != EXPECTED_CHAR_COUNT:
        raise ValueError(f"{row['image_name']}: invalid gt char boxes")
    return [box for box in boxes if box is not None]


def merged_predictions(gt: pd.DataFrame, pred: pd.DataFrame) -> pd.DataFrame:
    unknown = sorted(set(pred["image_name"]) - set(gt["image_name"]))
    if unknown:
        raise SystemExit(f"Prediction CSV contains unknown image_name values: {unknown}")
    return pred.merge(gt, on="image_name", how="left", suffixes=("_pred", "_gt"))


def clean_status(value: Any, invalid: bool, has_plate: bool, has_chars: bool) -> str:
    if invalid:
        return "invalid_prediction"
    if not is_empty_value(value):
        return str(value)
    if not has_plate:
        return "plate_not_found"
    if not has_chars:
        return "char_failed"
    return "success"


def clean_failure_reason(value: Any, parse_errors: list[str]) -> str:
    reasons = [reason for reason in parse_errors if reason]
    if not is_empty_value(value):
        reasons.append(str(value))
    return "; ".join(reasons)


def evaluate_rows(merged: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for _, row in merged.iterrows():
        pred_plate, plate_error = parse_plate_bbox(row["plate_bbox_pred"])
        pred_chars, char_error = parse_char_bboxes(row["char_bboxes_pred"])
        parse_errors = [error for error in (plate_error, char_error) if error]
        invalid = bool(parse_errors)

        gt_plate = gt_plate_bbox(row)
        gt_chars = gt_char_bboxes(row)
        plate_iou = 0.0 if invalid else bbox_iou(pred_plate, gt_plate)
        plate_center_error = math.nan if invalid else center_error(pred_plate, gt_plate)
        char_count_pred = len(pred_chars) if not invalid else 0
        char_count_correct = char_count_pred == EXPECTED_CHAR_COUNT
        char_iou = math.nan if invalid else mean_char_iou(pred_chars, gt_chars)
        char_bound_error = math.nan if invalid else boundary_error(pred_chars, gt_chars)
        over_split = char_count_pred > EXPECTED_CHAR_COUNT
        under_split = char_count_pred < EXPECTED_CHAR_COUNT
        plate_success_50 = plate_iou >= 0.5
        plate_success_70 = plate_iou >= 0.7
        end_to_end_success = (
            plate_success_50
            and char_count_correct
            and not math.isnan(char_iou)
            and char_iou >= END_TO_END_CHAR_IOU_THRESHOLD
        )
        status = clean_status(row["status"], invalid, pred_plate is not None, bool(pred_chars))
        failure_reason = clean_failure_reason(row["failure_reason"], parse_errors)

        rows.append(
            {
                "image_name": row["image_name"],
                "split": row["split"],
                "scene_type": row.get("scene_type", ""),
                "method": row["method"],
                "params": row.get("params", ""),
                "status": status,
                "failure_reason": failure_reason,
                "runtime_ms": pd.to_numeric(row.get("runtime_ms", math.nan), errors="coerce"),
                "vis_path": row.get("vis_path", ""),
                "plate_iou": plate_iou,
                "plate_center_error": plate_center_error,
                "plate_success_50": plate_success_50,
                "plate_success_70": plate_success_70,
                "char_count_pred": char_count_pred,
                "char_count_correct": char_count_correct,
                "char_mean_iou": char_iou,
                "char_boundary_error": char_bound_error,
                "over_split": over_split,
                "under_split": under_split,
                "end_to_end_success": end_to_end_success,
            }
        )
    return pd.DataFrame(rows)


def summarize_group(group: pd.DataFrame, split_name: str) -> dict[str, Any]:
    return {
        "method": group["method"].iloc[0],
        "split": split_name,
        "num_images": int(len(group)),
        "plate_success_rate_50": float(group["plate_success_50"].mean()),
        "plate_success_rate_70": float(group["plate_success_70"].mean()),
        "avg_plate_iou": float(group["plate_iou"].mean()),
        "avg_plate_center_error": float(group["plate_center_error"].mean()),
        "char_count_accuracy": float(group["char_count_correct"].mean()),
        "avg_char_iou": float(group["char_mean_iou"].mean()),
        "avg_char_boundary_error": float(group["char_boundary_error"].mean()),
        "over_split_count": int(group["over_split"].sum()),
        "under_split_count": int(group["under_split"].sum()),
        "end_to_end_success_rate": float(group["end_to_end_success"].mean()),
        "avg_runtime_ms": float(group["runtime_ms"].mean()),
        "invalid_prediction_count": int((group["status"] == "invalid_prediction").sum()),
    }


def build_method_summary(per_image: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for method, method_df in per_image.groupby("method", sort=True):
        rows.append(summarize_group(method_df, "all"))
        for split_name, split_df in method_df.groupby("split", sort=True):
            rows.append(summarize_group(split_df, str(split_name)))
    return pd.DataFrame(rows)


def build_failure_summary(per_image: pd.DataFrame) -> pd.DataFrame:
    failure_df = per_image.copy()
    failure_df["failure_reason"] = failure_df["failure_reason"].fillna("")
    failure_df.loc[failure_df["failure_reason"] == "", "failure_reason"] = "(none)"
    grouped = (
        failure_df.groupby(["method", "status", "failure_reason"], dropna=False)
        .size()
        .reset_index(name="count")
        .sort_values(["method", "status", "count"], ascending=[True, True, False])
    )
    return grouped


def write_outputs(per_image: pd.DataFrame, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    method_summary = build_method_summary(per_image)
    failure_summary = build_failure_summary(per_image)
    per_image.to_csv(out_dir / "per_image_metrics.csv", index=False, encoding="utf-8-sig")
    method_summary.to_csv(out_dir / "method_summary.csv", index=False, encoding="utf-8-sig")
    failure_summary.to_csv(out_dir / "failure_summary.csv", index=False, encoding="utf-8-sig")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gt", default="annotations/plate_char_annotations.csv", help="Ground-truth CSV.")
    parser.add_argument("--pred", required=True, help="Prediction CSV.")
    parser.add_argument("--out-dir", default="results/eval", help="Directory for evaluation outputs.")
    args = parser.parse_args()

    gt = load_ground_truth(Path(args.gt))
    pred = load_predictions(Path(args.pred))
    merged = merged_predictions(gt, pred)
    per_image = evaluate_rows(merged)
    write_outputs(per_image, Path(args.out_dir))

    print(f"Evaluated {len(per_image)} prediction rows")
    print(f"Wrote metrics to {Path(args.out_dir)}")
    summary = build_method_summary(per_image)
    all_rows = summary[summary["split"] == "all"]
    if not all_rows.empty:
        print(all_rows.to_string(index=False))


if __name__ == "__main__":
    main()
